In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [3]:
rng = np.random.default_rng(seed = 555)

1. How likely is it that you roll doubles when rolling two dice?

In [4]:
# determining the porbabilty of one fair six sided dice landing on any one side
one_dice = rng.integers(1,7, (100_000_000))
one_dice[:5]

array([3, 2, 6, 1, 6])

In [5]:
one_dice == 1

array([False, False, False, ..., False,  True, False])

In [6]:
(one_dice == 1).sum()

16673449

In [7]:
# Probability of one dice
(one_dice == 1).sum() / len(one_dice)

0.16673449

In [8]:
two_dice = rng.integers(1,7, (100_000_000, 2))

In [9]:
two_dice.shape

(100000000, 2)

In [10]:
two_dice[:,0] == two_dice[:,1]

array([False, False, False, ...,  True, False, False])

In [11]:
(two_dice[:,0] == two_dice[:,1]).sum()

16662928

In [12]:
(two_dice[:,0] == two_dice[:,1]).sum() / len(two_dice)

0.16662928

In [13]:
# there is 0.16667058 chance that doubles would be rolled.

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [14]:
eight_coins = rng.choice([0,1], (100_000_000,8))
eight_coins[:5]

array([[1, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 1, 0, 0]])

In [15]:
eight_count = (eight_coins.sum(axis=1)) == 3

In [16]:
eight_count.sum() / len(eight_coins)

0.21871144

In [17]:
# There would be a probabilty of 0.21873386 that exactly 3 coins would be head

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [18]:
two_billbo = rng.integers(1,5, (10_000_000, 2))
two_billbo[:10]

array([[2, 3],
       [1, 1],
       [4, 4],
       [3, 1],
       [1, 4],
       [2, 3],
       [2, 1],
       [3, 1],
       [1, 1],
       [3, 4]])

In [19]:
two_bil_sum = (two_billbo[:,0] + two_billbo[:,1] == 2).sum()

In [20]:
#Another way to select a specific digit
# two_billbo[:,0] == 1)  & (two_billbo[:,1] == 1

In [21]:
two_bil_sum / len(two_billbo)

0.062524

# There is a probability of 0.0623678 that a data sciecntist is on both bill boards assuming all cohorts have an equal number of students

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values



In [22]:
p_tarts = rng.normal(3,1.5,10_000_000)

In [23]:
p_tarts

array([1.44992563, 4.71533031, 3.22440482, ..., 1.77268118, 5.50839678,
       4.5862211 ])

In [24]:
reshape_p_tarts = p_tarts.reshape(-1,5)

In [25]:
reshape_p_tarts.shape

(2000000, 5)

In [26]:
sum_resape_p_tarts = (reshape_p_tarts.sum(axis=1) < 17).sum()

In [27]:
sum_resape_p_tarts / len(reshape_p_tarts)

0.724291

In [28]:
# There is a probability of 0.724384 that there will be poptarts availble on Friday afternoon

5. Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [29]:
male_height = rng.normal(178, 8 , 10_000_000)
female_height = rng.normal(170, 6 , 10_000_000)

In [30]:
# Index not necesaey but this is how you would index a one dimensional array for vector operations
# test_diff = female_height[:] > male_height[:]

In [31]:
stream_diff = female_height > male_height

In [32]:
stream_diff.sum() / len(stream_diff)

0.2119864

In [33]:
# There is be a proabability of 0.211905 that a randomnly selected woman would be taller than a randomly selected man

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?